import { Inter } from "next/font/google";
import { PrimeReactProvider , PrimeReactContext } from 'primereact/api';

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <PrimeReactProvider>
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
        </PrimeReactProvider>
  );
}
